numbers = [-1, 10, -4, -3, 7,8,5,3,9, 0]
print (numbers)
print(numbers[2])
print(numbers[2::2])
print(len(numbers))
print(numbers.sort)
mixed_list = (7, 6, "yoh", -4, "allo")
print(mixed_list)
print(mixed_list[2])
numbers.sort()
print(numbers)
numbers.append(23)
print(numbers)
numbers.insert(2,14)
print(numbers)
numbers.extend ([11, 12, 13])
print(numbers)
numbers.extend([24, 34, 35])
print(numbers)
numbers.remove(0)
print(numbers)